canvas_syllabus_export/urls.py
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('', include('syllabuspdf.urls', namespace='syllabuspdf')),
    path('admin/', admin.site.urls),
]

syllabuspdf/urls.py
from django.urls import path
from . import views
from lti_provider import views as lti_views

app_name = 'syllabuspdf'
urlpatterns = [
    path('lti/launch/', views.process_lti_launch_request_view, name='process_lti_launch_request'),
    path('lti/config/', lti_views.LTIConfigView.as_view(), name='get_lti_xml'),
	path('index/', views.index, name='index'),
    path('logger/', views.logger_view, name='logger_view'),
]

syllabuspdf/models.py
from django.db import models

# Create your models here.

syllabuspdf/forms.py
from django import forms

class SettingsForm(forms.Form):
	syllabus = forms.BooleanField(label="Syllabus Description", initial=True, required=False, label_suffix='')
	dated_events = forms.BooleanField(label="Dated", initial=True, required=False, label_suffix='')
	undated_events = forms.BooleanField(label="Undated", initial=False, required=False, label_suffix='')
	descriptions = forms.BooleanField(label="Descriptions", initial=False, required=False, label_suffix='')
	times = forms.BooleanField(label="Times", initial=True, required=False, label_suffix='')
	weights = forms.BooleanField(label="Assignment Group Weights", initial=False, required=False, label_suffix='')
	hidden_field = forms.CharField(widget=forms.HiddenInput(), initial="viewed", required=False, label_suffix='')

	

syllabuspdf/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponseBadRequest, HttpResponseServerError, HttpResponse, HttpResponseNotFound
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.conf import settings
from lti_provider.lti import LTI
from pylti.common import LTIException
from canvas_sdk.exceptions import (CanvasAPIError, InvalidOAuthTokenError)

from .apirequest import fetch_syllabus, fetch_allevents, fetch_assigngroups
from .forms import SettingsForm

import logging


logger = logging.getLogger('syllabuspdf')


@csrf_exempt
def process_lti_launch_request_view(request):
    '''
    Processes the lti launch request and redirects to the index view
    '''
    #True if this is a typical lti launch. False if not.
    is_basic_lti_launch = request.method == 'POST' and request.POST.get(
        'lti_message_type') == 'basic-lti-launch-request'

    lti = LTI(request_type="any", role_type="any")
    try:
        request_is_valid = lti.verify(request)
    except LTIException:  # oauth session may have timed out or the LTI key/secret pair may be wrong
        logger.exception("LTI launch failed")
        return HttpResponseBadRequest('<p>LTI launch failed. Please contact atg@fas.harvard.edu for assistance.<p>')

    if is_basic_lti_launch and request_is_valid:
        # Store the custom_canvas_course_id in the request's session attribute.
        course_id = request.POST.get('custom_canvas_course_id')
        user_id = request.POST.get('user_id')
        logger.info(f"LTI launch valid: course_id={course_id} user_id={user_id}")
        request.session['user_id'] = user_id
        request.session['course_id'] = course_id
        request.session.modified = True
        return redirect('syllabuspdf:index', permanent=False)
    else:
        logger.info(f"LTI launch invalid: is_basic_lti_launch={is_basic_lti_launch} request_is_valid={request_is_valid}")
        raise PermissionDenied


@csrf_exempt
def index(request):
    # Get course id from session
    try:
        course_id = request.session['course_id']
        user_id = request.session['user_id']
        logger.info(f"Syllabus index: course_id={course_id} user_id={user_id}")
    except:
        logger.error("Syllabus index: canvas course ID not found in session")
        raise Http404('Course ID not found')

    # Get content via API calls
    try:
        syllabus = fetch_syllabus(course_id)
        (dated, undated) = fetch_allevents(course_id)
        groups = fetch_assigngroups(course_id)
        logger.info(f"Syllabus index: Canvas API data loaded successfully: course_id={course_id} user_id={user_id}")
    except (CanvasAPIError, InvalidOAuthTokenError):
        logger.exception(f"Syllabus index: Canvas API error: course_id={course_id} user_id={user_id}")
        return HttpResponseServerError(f"Error: failed to load syllabus and assignment data from Canvas")

    # Check for initial load of page through presence of hidden field
    if 'hidden_field' in request.GET:
        form = SettingsForm(request.GET)
        if form.is_valid():
            form_settings = form.cleaned_data
    else:
        form = SettingsForm()
        form_settings = {
            'syllabus': True,
            'dated_events': True,
            'undated_events': False,
            'descriptions': False,
            'times': True,
            'weights': False,
            'hidden_field': "viewed"
        }

    # Populate events array based on toggled options
    events = []
    if form_settings['dated_events']:
        events += dated
    if form_settings['undated_events']:
        events += undated

    context = {
        'ga_tracking_id': settings.GA_TRACKING_ID,
        'syllabus': syllabus,
        'events': events,
        'groups': groups,
        'form': form,
        'settings': form_settings
    }
    return render(request, 'syllabuspdf/index.html', context)

@require_http_methods(["POST"])
@csrf_exempt
def logger_view(request):
    '''
    Logger API - to log onclick event from Generate PDF button
    '''
    # Note we could make this more dynamic and parameterize the request
    try:
        course_id = request.session['course_id']
        user_id = request.session['user_id']
        logger.info(f"Syllabus index: Syllabus PDF Generated: course_id={course_id} user_id={user_id}")
        return HttpResponse(status=200)
    except KeyError as e:
        logger.error(f"Syllabus index: Syllabus PDF Not Generated: canvas {e} not found in session")
        return HttpResponseNotFound(f'{e} not found')

syllabuspdf/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Canvas Syllabus Export{% endblock %}</title>
        
        {% block stylesheets %}{% endblock %}

        {% if ga_tracking_id %}
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id={{ ga_tracking_id }}"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '{{ ga_tracking_id }}');
        </script>
        {% endif %}
    </head>
    <body>
        {% block content %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

syllabuspdf/templates/syllabuspdf/index.html
{% extends "base.html" %}
{% load syllabuspdf_extras %}
{% load staticfiles %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'syllabuspdf/css/styles.css' %}" />
{% endblock %}

{% block content %}
<script>
	function call_logger() {
		// Note: non-blocking incase a syllabus is generated offline, could nest it in the .then()
		window.print();
		fetch('/logger/',
			{
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				}
			}
		)
	}
  </script>
<!-- Menu for toggling options and generating PDF -->
<header id="syllabus-export">
	<form action="{% url 'syllabuspdf:index' %}" method="get">
		<fieldset id="menu">
			<legend>Display:</legend>
			<div class="menu-params">
				<div class="menu-param">
					{{ form.syllabus }} 
					{{ form.syllabus.label_tag }}
				</div>
				<div class="menu-param">
					<b>Event Types</b> 
					{{ form.dated_events }} 
					{{ form.dated_events.label_tag }}
					{{ form.undated_events }} 
					{{ form.undated_events.label_tag }}
				</div>
				<div class="menu-param">
					<b>Event Properties</b> 
					{{ form.descriptions }} 
					{{ form.descriptions.label_tag }} 
					{{ form.times }} 
					{{ form.times.label_tag }}
				</div>
				<div class="menu-param">
					{{ form.weights }} 
					{{ form.weights.label_tag }}
				</div>
			</div>
			<div class="menu-btns">
				<input id="id_hidden_field" name="hidden_field" type="hidden" value= "{{ form.hidden_field.value }}" />
				<input type="submit" class="btn" value="Preview"/>
				<input type="button" class="btn" onclick="call_logger()" value="Generate PDF"/>
			</div>
		</fieldset>
	</form>
	<h2>Preview:</h2>
</header>

<!-- Syllabus body -->
<!-- Divs used to fix Webkit bug of splitting table rows-->
{% if syllabus and settings.syllabus %}
	{% autoescape off %} {{ syllabus }} {% endautoescape %}
{% endif %}

{% if settings.dated_events or settings.undated_events %}
<div> <b> Course Schedule </b> </div>
<div class="table" id="events">
	<div class="head">
		<div class="row">
			<div class="cell" style="width: 20%;">Date</div>
	    	<div class="cell" style="width: 80%;">Details</div>
		</div>
	</div>
	{% if events %}
	{% for event in events %}
	<div class="row">
	    <div class="cell"> {{ event.end_at |format_date }} </div>
	    <div class="cell">
	    	<span class="event"> 
	    		<span class="event_title">
	    			<b> {{ event.title }} </b>
	    		</span>
	    		{% if settings.times %}
	    		<span class="event_time">
	     			<i> {% if 'assignment' in event %}
	    			{% format_time event.start_at event.end_at 'assignment' %}
	    			{% else %}
	    			{% format_time event.start_at event.end_at 'calendar' %}
	    			{% endif %} </i>
	    		</span>
	    		{% endif %}
	    	</span>
		</div>
	</div>
	<div class="row">
	  	<div class="cell"></div>
	  	{% if settings.descriptions %}
	  	{% autoescape off %}
	  	<div class="cell"> {{ event.description|escape_None }}</div>
	  	{% endautoescape %}
	  	{% endif %}
	</div>
	{% endfor %}
	{% endif %}

</div>
{% endif %}

<!-- Assignment Weights Table (divs inserted to work around Webkit bug of splitting table rows) -->
{% if groups and settings.weights %}
<div> <b> Assignment Weights </b> </div>
<div class="table" id="weights">
    <div class="head">
    	<div class="row">
    		<div class="cell">Group</div>
        	<div class="cell">Weight</div>
    	</div>
    </div>
{% for group in groups %}
    {% if group.group_weight != 0 %}
    <div class="row">
          <div class="cell"> {{ group.name }} </div>
          <div class="cell"> {{ group.group_weight }}% </div>
    </div>
        {% endif %}
{% endfor %}
</div>
{% endif %}
{% endblock %}